sonar.projectKey=ProDispatch
sonar.organization=prodispatch
sonar.projectName=ProDispatch
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/bin/**,**/obj/**,**/*.cshtml
sonar.coverageReportPaths=**/TestResults/**/coverage.cobertura.xml
